### ISSUE TITLE
Plex json help

### ISSUE THREAD

**Issue by sachaw** [ChrisRidings/CastV2inPHP#3]
Hi, I have got Plex control working, but now I want to initiate playing media, I had a look at `CCPlexPlayer.php` and `Plex->Play();` expects a JSON payload, could you please provide me with the payload format that it will accept for casting media from my Plex server, thanks.

**Comment by ChrisRidings** [comment]
It takes a format like this:

{"contentId":"\/library\/metadata\/9795","streamType":"BUFFERED","contentType":"video","customData":{"offset":0,"directPlay":true,"directStream":true,"subtitleSize":100,"audioBoost":100,"server":{"machineIdentifier":"[identifierhere]","transcoderVideo":true,"transcoderVideoRemuxOnly":false,"transcoderAudio":true,"version":"1.4.3.3433","myPlexSubscription":true,"isVerifiedHostname":true,"protocol":"https","address":"[plex-local-dns-name]","port":32400,"accessToken":"transient-[accesstokenhere]","user":{"username":"[usernamehere]"},"containerKey":"327?own=1&window=200"},"autoplay":true,"currentTime":0}}}

The plex class was written to help enable this project: https://github.com/d8ahazard/Phlex . So you could take a look there to see how it's built up (you may or may not need to look at older versions as I think it's using a different method now).
